"""Info of Measurements of PickingLab for synchronization.

Created:
    21.08.2025

Author:
    Fernando Moya Rueda

Copyright:
    MotionMiners GmbH, Emil-Figge Str. 80, 44227 Dortmund, 2024
"""

MEASUREMENTS_INFO = {
    1: {
        1: {
            "subject_id": 1,
            "session_id": 1,
            "imu_set_id": 1,
            "imu_set": "44-C",
            "imu_file_name": "S01_44-C_imu_data.csv",
            "ble_file_name": "S01_44-C_ble.csv",
            "labels_file_name": "S01_44-C_labels.csv",
            "predictionsMM_file_name": "S01_44-C_predictions.csv",
            "predictionsMM_car_file_name": "S01_44-C_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S01_44-C_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-C_2024-05-22_09_34_28_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S01_44-C_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S01_44-C_time_interval.csv",
            "dyn_closeness_arr": "S01_44-C_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S01_44-C_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (33_792, 760_437),
            ],
            "annotation_sync_ranges": [
                (324, 218094),
            ],
        },
        2: {
            "subject_id": 1,
            "session_id": 1,
            "imu_set_id": 2,
            "imu_set": "44-D",
            "imu_file_name": "S01_44-D_imu_data.csv",
            "ble_file_name": "S01_44-D_ble.csv",
            "labels_file_name": "S01_44-D_labels.csv",
            "predictionsMM_file_name": "S01_44-D_predictions.csv",
            "predictionsMM_car_file_name": "S01_44-D_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S01_44-D_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-D_2024-05-22_09_34_54_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S01_44-D_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S01_44-D_time_interval.csv",
            "dyn_closeness_arr": "S01_44-D_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S01_44-D_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (31_181, 757_845),
            ],
            "annotation_sync_ranges": [
                (324, 218094),
            ],
        },
    },
    2: {
        1: {
            "subject_id": 2,
            "session_id": 1,
            "imu_set_id": 1,
            "imu_set": "44-A",
            "imu_file_name": "S02_44-A_imu_data.csv",
            "ble_file_name": "S02_44-A_ble.csv",
            "labels_file_name": "S02_44-A_labels.csv",
            "predictionsMM_file_name": "S02_44-A_predictions.csv",
            "predictionsMM_car_file_name": "S02_44-A_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S02_44-A_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-A_2024-05-22_09_33_17_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S02_44-A_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S02_44-A_time_interval.csv",
            "dyn_closeness_arr": "S02_44-A_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S02_44-A_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (40_388, 627_737),
            ],
            "annotation_sync_ranges": [
                (181, 176147),
            ],
        },
        2: {
            "subject_id": 2,
            "session_id": 1,
            "imu_set_id": 2,
            "imu_set": "44-B",
            "imu_file_name": "S02_44-B_imu_data.csv",
            "ble_file_name": "S02_44-B_ble.csv",
            "labels_file_name": "S02_44-B_labels.csv",
            "predictionsMM_file_name": "S02_44-B_predictions.csv",
            "predictionsMM_car_file_name": "S02_44-B_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S02_44-B_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-B_2024-05-22_09_33_49_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S02_44-B_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S02_44-B_time_interval.csv",
            "dyn_closeness_arr": "S02_44-B_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S02_44-B_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (37_257, 624_448),
            ],
            "annotation_sync_ranges": [
                (181, 176147),
            ],
        },
    },
    3: {
        1: {
            "subject_id": 3,
            "session_id": 1,
            "imu_set_id": 1,
            "imu_set": "44-E",
            "imu_file_name": "S03_44-E_imu_data.csv",
            "ble_file_name": "S03_44-E_ble.csv",
            "labels_file_name": "S03_44-E_labels.csv",
            "predictionsMM_file_name": "S03_44-E_predictions.csv",
            "predictionsMM_car_file_name": "S03_44-E_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S03_44-E_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-E_2024-05-22_09_35_38_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S03_44-E_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S03_44-E_time_interval.csv",
            "dyn_closeness_arr": "S03_44-E_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S03_44-E_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (25_983, 561_373),
            ],
            "annotation_sync_ranges": [
                (81, 160540),
            ],
        },
        2: {
            "subject_id": 3,
            "session_id": 1,
            "imu_set_id": 2,
            "imu_set": "44-F",
            "imu_file_name": "S03_44-F_imu_data.csv",
            "ble_file_name": "S03_44-F_ble.csv",
            "labels_file_name": "S03_44-F_labels.csv",
            "predictionsMM_file_name": "S03_44-F_predictions.csv",
            "predictionsMM_car_file_name": "S03_44-F_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S03_44-F_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-F_2024-05-22_09_36_05_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S03_44-F_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S03_44-F_time_interval.csv",
            "dyn_closeness_arr": "S03_44-F_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S03_44-F_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (23_304, 558_693),
            ],
            "annotation_sync_ranges": [
                (81, 160540),
            ],
        },
    },
    4: {
        1: {
            "subject_id": 4,
            "session_id": 2,
            "imu_set_id": 1,
            "imu_set": "44-E",
            "imu_file_name": "S04_44-E_imu_data.csv",
            "ble_file_name": "S04_44-E_ble.csv",
            "labels_file_name": "S04_44-E_labels.csv",
            "predictionsMM_file_name": "S04_44-E_predictions.csv",
            "predictionsMM_car_file_name": "S04_44-E_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S04_44-E_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-E_2024-05-22_14_07_29_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S04_44-E_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S04_44-E_time_interval.csv",
            "dyn_closeness_arr": "S04_44-E_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S04_44-E_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (80_044, 894_873),
            ],
            "annotation_sync_ranges": [
                (1036, 245230),
            ],
        },
        2: {
            "subject_id": 4,
            "session_id": 2,
            "imu_set_id": 2,
            "imu_set": "44-F",
            "imu_file_name": "S04_44-F_imu_data.csv",
            "ble_file_name": "S04_44-F_ble.csv",
            "labels_file_name": "S04_44-F_labels.csv",
            "predictionsMM_file_name": "S04_44-F_predictions.csv",
            "predictionsMM_car_file_name": "S04_44-F_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S04_44-F_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-F_2024-05-22_14_07_37_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S04_44-F_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S04_44-F_time_interval.csv",
            "dyn_closeness_arr": "S04_44-F_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S04_44-F_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (79_180, 894_001),
            ],
            "annotation_sync_ranges": [
                (1036, 245230),
            ],
        },
    },
    5: {
        1: {
            "subject_id": 5,
            "session_id": 2,
            "imu_set_id": 1,
            "imu_set": "44-A",
            "imu_file_name": "S05_44-A_imu_data.csv",
            "ble_file_name": "S05_44-A_ble.csv",
            "labels_file_name": "S05_44-A_labels.csv",
            "predictionsMM_file_name": "S05_44-A_predictions.csv",
            "predictionsMM_car_file_name": "S05_44-A_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S05_44-A_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-A_2024-05-22_14_06_56_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S05_44-A_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S05_44-A_time_interval.csv",
            "dyn_closeness_arr": "S05_44-A_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S05_44-A_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (82_923, 677_153),
            ],
            "annotation_sync_ranges": [
                (924, 179006),
            ],
        },
        2: {
            "subject_id": 5,
            "session_id": 2,
            "imu_set_id": 2,
            "imu_set": "44-B",
            "imu_file_name": "S05_44-B_imu_data.csv",
            "ble_file_name": "S05_44-B_ble.csv",
            "labels_file_name": "S05_44-B_labels.csv",
            "predictionsMM_file_name": "S05_44-B_predictions.csv",
            "predictionsMM_car_file_name": "S05_44-B_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S05_44-B_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-B_2024-05-22_14_07_04_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S05_44-B_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S05_44-B_time_interval.csv",
            "dyn_closeness_arr": "S05_44-B_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S05_44-B_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (82_119, 676_349),
            ],
            "annotation_sync_ranges": [
                (924, 179006),
            ],
        },
    },
    6: {
        1: {
            "subject_id": 6,
            "session_id": 2,
            "imu_set_id": 1,
            "imu_set": "44-C",
            "imu_file_name": "S06_44-C_imu_data.csv",
            "ble_file_name": "S06_44-C_ble.csv",
            "labels_file_name": "S06_44-C_labels.csv",
            "predictionsMM_file_name": "S06_44-C_predictions.csv",
            "predictionsMM_car_file_name": "S06_44-C_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S06_44-C_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-C_2024-05-22_14_07_13_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S06_44-C_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S06_44-C_time_interval.csv",
            "dyn_closeness_arr": "S06_44-C_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S06_44-C_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (81_487, 582_734),
            ],
            "annotation_sync_ranges": [
                (992, 151206),
            ],
        },
        2: {
            "subject_id": 6,
            "session_id": 2,
            "imu_set_id": 2,
            "imu_set": "44-D",
            "imu_file_name": "S06_44-D_imu_data.csv",
            "ble_file_name": "S06_44-D_ble.csv",
            "labels_file_name": "S06_44-D_labels.csv",
            "predictionsMM_file_name": "S06_44-D_predictions.csv",
            "predictionsMM_car_file_name": "S06_44-D_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S06_44-D_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-D_2024-05-22_14_07_21_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S06_44-D_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S06_44-D_time_interval.csv",
            "dyn_closeness_arr": "S06_44-D_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S06_44-D_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (80_668, 581_894),
            ],
            "annotation_sync_ranges": [
                (992, 151206),
            ],
        },
    },
    7: {
        1: {
            "subject_id": 7,
            "session_id": 3,
            "imu_set_id": 1,
            "imu_set": "44-A",
            "imu_file_name": "S07_44-A_imu_data.csv",
            "ble_file_name": "S07_44-A_ble.csv",
            "labels_file_name": "S07_44-A_labels.csv",
            "predictionsMM_file_name": "S07_44-A_predictions.csv",
            "predictionsMM_car_file_name": "S07_44-A_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S07_44-A_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-A_2024-05-23_09_32_59_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S07_44-A_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S07_44-A_time_interval.csv",
            "dyn_closeness_arr": "S07_44-A_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S07_44-A_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (48_598, 655_683),
            ],
            "annotation_sync_ranges": [
                (680, 182620),
            ],
        },
        2: {
            "subject_id": 7,
            "session_id": 3,
            "imu_set_id": 2,
            "imu_set": "44-B",
            "imu_file_name": "S07_44-B_imu_data.csv",
            "ble_file_name": "S07_44-B_ble.csv",
            "labels_file_name": "S07_44-B_labels.csv",
            "predictionsMM_file_name": "S07_44-B_predictions.csv",
            "predictionsMM_car_file_name": "S07_44-B_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S07_44-B_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-B_2024-05-23_09_33_03_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S07_44-B_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S07_44-B_time_interval.csv",
            "dyn_closeness_arr": "S07_44-B_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S07_44-B_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (48_205, 655_282),
            ],
            "annotation_sync_ranges": [
                (680, 182620),
            ],
        },
    },
    8: {
        1: {
            "subject_id": 8,
            "session_id": 3,
            "imu_set_id": 1,
            "imu_set": "44-C",
            "imu_file_name": "S08_44-C_imu_data.csv",
            "ble_file_name": "S08_44-C_ble.csv",
            "labels_file_name": "S08_44-C_labels.csv",
            "predictionsMM_file_name": "S08_44-C_predictions.csv",
            "predictionsMM_car_file_name": "S08_44-C_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S08_44-C_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-C_2024-05-23_09_35_30_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S08_44-C_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S08_44-C_time_interval.csv",
            "dyn_closeness_arr": "S08_44-C_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S08_44-C_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (35_115, 517_704),
            ],
            "annotation_sync_ranges": [
                (1161, 145762),
            ],
        },
        2: {
            "subject_id": 8,
            "session_id": 3,
            "imu_set_id": 2,
            "imu_set": "44-D",
            "imu_file_name": "S08_44-D_imu_data.csv",
            "ble_file_name": "S08_44-D_ble.csv",
            "labels_file_name": "S08_44-D_labels.csv",
            "predictionsMM_file_name": "S08_44-D_predictions.csv",
            "predictionsMM_car_file_name": "S08_44-D_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S08_44-D_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-D_2024-05-23_09_35_31_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S08_44-D_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S08_44-D_time_interval.csv",
            "dyn_closeness_arr": "S08_44-D_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S08_44-D_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (35_023, 517_510),
            ],
            "annotation_sync_ranges": [
                (1161, 145762),
            ],
        },
    },
    9: {
        1: {
            "subject_id": 9,
            "session_id": 3,
            "imu_set_id": 1,
            "imu_set": "44-E",
            "imu_file_name": "S09_44-E_imu_data.csv",
            "ble_file_name": "S09_44-E_ble.csv",
            "labels_file_name": "S09_44-E_labels.csv",
            "predictionsMM_file_name": "S09_44-E_predictions.csv",
            "predictionsMM_car_file_name": "S09_44-E_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S09_44-E_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-E_2024-05-23_09_36_57_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S09_44-E_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S09_44-E_time_interval.csv",
            "dyn_closeness_arr": "S09_44-E_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S09_44-E_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (25_700, 774_396),
            ],
            "annotation_sync_ranges": [
                (937, 225315),
            ],
        },
        2: {
            "subject_id": 9,
            "session_id": 3,
            "imu_set_id": 2,
            "imu_set": "44-F",
            "imu_file_name": "S09_44-F_imu_data.csv",
            "ble_file_name": "S09_44-F_ble.csv",
            "labels_file_name": "S09_44-F_labels.csv",
            "predictionsMM_file_name": "S09_44-F_predictions.csv",
            "predictionsMM_car_file_name": "S09_44-F_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S09_44-F_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-F_2024-05-23_09_37_02_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S09_44-F_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S09_44-F_time_interval.csv",
            "dyn_closeness_arr": "S09_44-F_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S09_44-F_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (25_202, 773_898),
            ],
            "annotation_sync_ranges": [
                (937, 225315),
            ],
        },
    },
    10: {
        1: {
            "subject_id": 10,
            "session_id": 4,
            "imu_set_id": 1,
            "imu_set": "44-C",
            "imu_file_name": "S10_44-C_imu_data.csv",
            "ble_file_name": "S10_44-C_ble.csv",
            "labels_file_name": "S10_44-C_labels.csv",
            "predictionsMM_file_name": "S10_44-C_predictions.csv",
            "predictionsMM_car_file_name": "S10_44-C_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S10_44-C_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-C_2024-05-23_14_22_22_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S10_44-C_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S10_44-C_time_interval.csv",
            "dyn_closeness_arr": "S10_44-C_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S10_44-C_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (34_702, 36_412),  # 34_702
            ],
            "annotation_sync_ranges": [
                (559, 199106),
            ],
        },
        2: {
            "subject_id": 10,
            "session_id": 4,
            "imu_set_id": 2,
            "imu_set": "44-D",
            "imu_file_name": "S10_44-D_imu_data.csv",
            "ble_file_name": "S10_44-D_ble.csv",
            "labels_file_name": "S10_44-D_labels.csv",
            "predictionsMM_file_name": "S10_44-D_predictions.csv",
            "predictionsMM_car_file_name": "S10_44-D_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S10_44-D_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-D_2024-05-23_14_22_27_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S10_44-D_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S10_44-D_time_interval.csv",
            "dyn_closeness_arr": "S10_44-D_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S10_44-D_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (34_141, 696_638),
            ],
            "annotation_sync_ranges": [
                (559, 199106),
            ],
        },
    },
    11: {
        1: {
            "subject_id": 11,
            "session_id": 4,
            "imu_set_id": 1,
            "imu_set": "44-E",
            "imu_file_name": "S11_44-E_imu_data.csv",
            "ble_file_name": "S11_44-E_ble.csv",
            "labels_file_name": "S11_44-E_labels.csv",
            "predictionsMM_file_name": "S11_44-E_predictions.csv",
            "predictionsMM_car_file_name": "S11_44-E_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S11_44-E_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-E_2024-05-23_14_24_10_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S11_44-E_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S11_44-E_time_interval.csv",
            "dyn_closeness_arr": "S11_44-E_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S11_44-E_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (22_873, 580_526),
            ],
            "annotation_sync_ranges": [
                (270, 167491),
            ],
        },
        2: {
            "subject_id": 11,
            "session_id": 4,
            "imu_set_id": 2,
            "imu_set": "44-F",
            "imu_file_name": "S11_44-F_imu_data.csv",
            "ble_file_name": "S11_44-F_ble.csv",
            "labels_file_name": "S11_44-F_labels.csv",
            "predictionsMM_file_name": "S11_44-F_predictions.csv",
            "predictionsMM_car_file_name": "S11_44-F_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S11_44-F_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-F_2024-05-23_14_24_16_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S11_44-F_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S11_44-F_time_interval.csv",
            "dyn_closeness_arr": "S11_44-F_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S11_44-F_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (22_303, 579_964),
            ],
            "annotation_sync_ranges": [
                (270, 167491),
            ],
        },
    },
    12: {
        1: {
            "subject_id": 12,
            "session_id": 4,
            "imu_set_id": 1,
            "imu_set": "44-A",
            "imu_file_name": "S12_44-A_imu_data.csv",
            "ble_file_name": "S12_44-A_ble.csv",
            "labels_file_name": "S12_44-A_labels.csv",
            "predictionsMM_file_name": "S12_44-A_predictions.csv",
            "predictionsMM_car_file_name": "S12_44-A_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S12_44-A_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-A_2024-05-23_14_21_19_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S12_44-A_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S12_44-A_time_interval.csv",
            "dyn_closeness_arr": "S12_44-A_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S12_44-A_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (39_832, 764_592),
            ],
            "annotation_sync_ranges": [
                (217, 217431),
            ],
        },
        2: {
            "subject_id": 12,
            "session_id": 4,
            "imu_set_id": 2,
            "imu_set": "44-B",
            "imu_file_name": "S12_44-B_imu_data.csv",
            "ble_file_name": "S12_44-B_ble.csv",
            "labels_file_name": "S12_44-B_labels.csv",
            "predictionsMM_file_name": "S12_44-B_predictions.csv",
            "predictionsMM_car_file_name": "S12_44-B_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S12_44-B_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-B_2024-05-23_14_21_23_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S12_44-B_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S12_44-B_time_interval.csv",
            "dyn_closeness_arr": "S12_44-B_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S12_44-B_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (39_453, 764_202),
            ],
            "annotation_sync_ranges": [
                (217, 217431),
            ],
        },
    },
    13: {
        1: {
            "subject_id": 13,
            "session_id": 5,
            "imu_set_id": 1,
            "imu_set": "44-A",
            "imu_file_name": "S13_44-A_imu_data.csv",
            "ble_file_name": "S13_44-A_ble.csv",
            "labels_file_name": "S13_44-A_labels.csv",
            "predictionsMM_file_name": "S13_44-A_predictions.csv",
            "predictionsMM_car_file_name": "S13_44-A_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S13_44-A_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-A_2024-05-24_09_25_08_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S13_44-A_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S13_44-A_time_interval.csv",
            "dyn_closeness_arr": "S13_44-A_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S13_44-A_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (74_287, 604_478),
            ],
            "annotation_sync_ranges": [
                (671, 159567),
            ],
        },
        2: {
            "subject_id": 13,
            "session_id": 5,
            "imu_set_id": 2,
            "imu_set": "44-B",
            "imu_file_name": "S13_44-B_imu_data.csv",
            "ble_file_name": "S13_44-B_ble.csv",
            "labels_file_name": "S13_44-B_labels.csv",
            "predictionsMM_file_name": "S13_44-B_predictions.csv",
            "predictionsMM_car_file_name": "S13_44-B_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S13_44-B_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-B_2024-05-24_09_25_13_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S13_44-B_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S13_44-B_time_interval.csv",
            "dyn_closeness_arr": "S13_44-B_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S13_44-B_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (73_875, 604_027),
            ],
            "annotation_sync_ranges": [
                (671, 159567),
            ],
        },
    },
    14: {
        1: {
            "subject_id": 14,
            "session_id": 5,
            "imu_set_id": 1,
            "imu_set": "44-C",
            "imu_file_name": "S14_44-C_imu_data.csv",
            "ble_file_name": "S14_44-C_ble.csv",
            "labels_file_name": "S14_44-C_labels.csv",
            "predictionsMM_file_name": "S14_44-C_predictions.csv",
            "predictionsMM_car_file_name": "S14_44-C_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S14_44-C_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-C_2024-05-24_09_28_30_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S14_44-C_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S14_44-C_time_interval.csv",
            "dyn_closeness_arr": "S14_44-C_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S14_44-C_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (53_263, 982_688),
            ],
            "annotation_sync_ranges": [
                (385, 278952),
            ],
        },
        2: {
            "subject_id": 14,
            "session_id": 5,
            "imu_set_id": 2,
            "imu_set": "44-D",
            "imu_file_name": "S14_44-D_imu_data.csv",
            "ble_file_name": "S14_44-D_ble.csv",
            "labels_file_name": "S14_44-D_labels.csv",
            "predictionsMM_file_name": "S14_44-D_predictions.csv",
            "predictionsMM_car_file_name": "S14_44-D_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S14_44-D_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-D_2024-05-24_09_28_37_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S14_44-D_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S14_44-D_time_interval.csv",
            "dyn_closeness_arr": "S14_44-D_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S14_44-D_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (52_421, 981_966),
            ],
            "annotation_sync_ranges": [
                (385, 278952),
            ],
        },
    },
    15: {
        1: {
            "subject_id": 15,
            "session_id": 5,
            "imu_set_id": 1,
            "imu_set": "44-E",
            "imu_file_name": "S15_44-E_imu_data.csv",
            "ble_file_name": "S15_44-E_ble.csv",
            "labels_file_name": "S15_44-E_labels.csv",
            "predictionsMM_file_name": "S15_44-E_predictions.csv",
            "predictionsMM_car_file_name": "S15_44-E_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S15_44-E_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-E_2024-05-24_09_31_41_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S15_44-E_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S15_44-E_time_interval.csv",
            "dyn_closeness_arr": "S15_44-E_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S15_44-E_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (32_982, 723_385),
            ],
            "annotation_sync_ranges": [
                (34, 206936),
            ],
        },
        2: {
            "subject_id": 15,
            "session_id": 5,
            "imu_set_id": 2,
            "imu_set": "44-F",
            "imu_file_name": "S15_44-F_imu_data.csv",
            "ble_file_name": "S15_44-F_ble.csv",
            "labels_file_name": "S15_44-F_labels.csv",
            "predictionsMM_file_name": "S15_44-F_predictions.csv",
            "predictionsMM_car_file_name": "S15_44-F_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S15_44-F_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-F_2024-05-24_09_31_45_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S15_44-F_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S15_44-F_time_interval.csv",
            "dyn_closeness_arr": "S15_44-F_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S15_44-F_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (32_482, 722_954),
            ],
            "annotation_sync_ranges": [
                (34, 206936),
            ],
        },
    },
    16: {
        1: {
            "subject_id": 16,
            "session_id": 6,
            "imu_set_id": 1,
            "imu_set": "44-A",
            "imu_file_name": "S16_44-A_imu_data.csv",
            "ble_file_name": "S16_44-A_ble.csv",
            "labels_file_name": "S16_44-A_labels.csv",
            "predictionsMM_file_name": "S16_44-A_predictions.csv",
            "predictionsMM_car_file_name": "S16_44-A_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S16_44-A_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-A_2024-05-24_14_18_02_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S16_44-A_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S16_44-A_time_interval.csv",
            "dyn_closeness_arr": "S16_44-A_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S16_44-A_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (59_340, 641_971),
            ],
            "annotation_sync_ranges": [
                (935, 175536),
            ],
        },
        2: {
            "subject_id": 16,
            "session_id": 6,
            "imu_set_id": 2,
            "imu_set": "44-B",
            "imu_file_name": "S16_44-B_imu_data.csv",
            "ble_file_name": "S16_44-B_ble.csv",
            "labels_file_name": "S16_44-B_labels.csv",
            "predictionsMM_file_name": "S16_44-B_predictions.csv",
            "predictionsMM_car_file_name": "S16_44-B_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S16_44-B_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-B_2024-05-24_14_18_04_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S16_44-B_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S16_44-B_time_interval.csv",
            "dyn_closeness_arr": "S16_44-B_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S16_44-B_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (59_193, 641_835),
            ],
            "annotation_sync_ranges": [
                (935, 175536),
            ],
        },
    },
    17: {
        1: {
            "subject_id": 17,
            "session_id": 6,
            "imu_set_id": 1,
            "imu_set": "44-C",
            "imu_file_name": "S17_44-C_imu_data.csv",
            "ble_file_name": "S17_44-C_ble.csv",
            "labels_file_name": "S17_44-C_labels.csv",
            "predictionsMM_file_name": "S17_44-C_predictions.csv",
            "predictionsMM_car_file_name": "S17_44-C_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S17_44-C_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-C_2024-05-24_14_19_40_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S17_44-C_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S17_44-C_time_interval.csv",
            "dyn_closeness_arr": "S17_44-C_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S17_44-C_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (50_890, 530_166),
            ],
            "annotation_sync_ranges": [
                (1315, 144959),
            ],
        },
        2: {
            "subject_id": 17,
            "session_id": 6,
            "imu_set_id": 2,
            "imu_set": "44-D",
            "imu_file_name": "S17_44-D_imu_data.csv",
            "ble_file_name": "S17_44-D_ble.csv",
            "labels_file_name": "S17_44-D_labels.csv",
            "predictionsMM_file_name": "S17_44-D_predictions.csv",
            "predictionsMM_car_file_name": "S17_44-D_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S17_44-D_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-D_2024-05-24_14_19_44_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S17_44-D_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S17_44-D_time_interval.csv",
            "dyn_closeness_arr": "S17_44-D_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S17_44-D_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (50_521, 529_793),
            ],
            "annotation_sync_ranges": [
                (1315, 144959),
            ],
        },
    },
    18: {
        1: {
            "subject_id": 18,
            "session_id": 6,
            "imu_set_id": 1,
            "imu_set": "44-E",
            "imu_file_name": "S18_44-E_imu_data.csv",
            "ble_file_name": "S18_44-E_ble.csv",
            "labels_file_name": "S18_44-E_labels.csv",
            "predictionsMM_file_name": "S18_44-E_predictions.csv",
            "predictionsMM_car_file_name": "S18_44-E_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S18_44-E_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-E_2024-05-24_14_22_13_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S18_44-E_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S18_44-E_time_interval.csv",
            "dyn_closeness_arr": "S18_44-E_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S18_44-E_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (36_566, 713_329),
            ],
            "annotation_sync_ranges": [
                (1624, 204469),
            ],
        },
        2: {
            "subject_id": 18,
            "session_id": 6,
            "imu_set_id": 2,
            "imu_set": "44-F",
            "imu_file_name": "S18_44-F_imu_data.csv",
            "ble_file_name": "S18_44-F_ble.csv",
            "labels_file_name": "S18_44-F_labels.csv",
            "predictionsMM_file_name": "S18_44-F_predictions.csv",
            "predictionsMM_car_file_name": "S18_44-F_CAR_predictions.csv",
            "predictionsMM_heights_file_name": "S18_44-F_heights_predictions.csv",
            "predictionsMM_fingerprinting_file_name": "44-F_2024-05-24_14_22_25_mpi_prediction.csv",
            "predictionsMM_fingerprinting_sync_file_name": "S18_44-F_fingerprinting_mpi_prediction.csv",
            "imu_time_interval_raw": "S18_44-F_time_interval.csv",
            "dyn_closeness_arr": "S18_44-F_dyn_closeness_arr.csv",
            "dyn_usage_arr": "S18_44-F_dyn_usage_arr.csv",
            "imu_data_sync_ranges": [
                (35_410, 712_181),
            ],
            "annotation_sync_ranges": [
                (1624, 204469),
            ],
        },
    },
}
